default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: username
  password: password
  host: localhost

development:
  <<: *default
  database: web_shop_db

test:
  <<: *default
  database: web_shop_test_db
