# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 051922717be06a54944f2b54db780fdb48bf2585780ad9e2314e573fdda561c6ee210ae9afb269bcba0270048aa48627af5f56621c9d7c73c2db38cfb31ad04e

test:
  secret_key_base: f5f064ae8de6fd75a85980def67f7a5b31bb5146531aca46c4d9bcba8b38b551a099bd4cc7c66b70e84f767cbaea08a71143cfc5634b504e278511205eef6ba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
